# Generated by Django 3.1.2 on 2020-11-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptspinneruser',
            name='is_subscribed',
        ),
        migrations.AddField(
            model_name='scriptspinneruser',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scriptspinneruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email address'),
        ),
    ]
